name: "Run tests in solution"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MS_NUGET_URL: https://nuget.pkg.github.com/microsoft/index.json
    steps:
      - name: Install
        uses: ${{github.repository}}/.github/workflows/install-dependencies.yml@${{github.ref_name || 'main'}}
      - name: Test
        run: dotnet test --no-restore