name: "Run tests in solution"
on: [push]
jobs:
  install:
    uses: ./.github/workflows/install-dependencies.yml
  test:
    runs-on: ubuntu-latest
    env:
      MS_NUGET_URL: https://nuget.pkg.github.com/microsoft/index.json
    steps:
      - name: Test
        run: dotnet test --no-restore