name: "Run tests in solution"
on: [push]
jobs:
  install:
    uses: ./.github/workflows/install-dependencies.yml
    secrets:
      user: ${{secrets.NUGET_USER}}
      token: ${{secrets.NUGET_PASSWORD}}
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Test
        run: dotnet test --no-restore